name: ❓ Demande d'informations
description: Une question sur le fonctionnement de la plateforme ? Sur les choix faits ?
labels: ["question"]
projects: ["Geoplateforme/1"]
body:

  - type: textarea
    id: description
    attributes:
      label: Vos questions
    validations:
      required: true
