name: 🚀 Documentation à améliorer
description: Demande d'ajout d'explications dans la documentation
labels: ["enhancement","documentation"]
projects: ["Geoplateforme/1"]
body:

  - type: markdown
    attributes:
      value: |
        Vous pouvez proposer des explications facilitant la compréhension via une pull request sur le dépôt de documentation

  - type: dropdown
    id: documentation
    attributes:
      label: Documentation concernée
      description: Quelle documentation est concernée par la demande de précisions
      options:
        - Synthèse des concepts de l'entrepôt
        - Briques applicatives de l'entrepôt
        - Gestion vecteur - Alimentation et diffusion simple
        - Gestion vecteur - Alimentation par mise à jour
        - Gestion raster - Alimentation et diffusion simple
        - Gestion raster - Alimentation par mise à jour
        - Gestion raster - Gestion de données MNT
        - Gestion d'archives - Alimentation et diffusion simple
        - Gestion des annexes
        - Gestion des métadonnées
        - Authentification - Contrôle des accès à l'API
        - Authentification - Contrôle des accès aux services de diffusion
        - Administration - Gestion des membres d'une communauté
        - Administration - Créer et gérer un espace de travail
        - Divers - Mise en place d'un groupe thématique de couches
    validations:
      required: false

  - type: input
    id: page
    attributes:
      label: Page concernée
      description: URL de la page de documentation manquant de précisions
    validations:
      required: false

  - type: textarea
    id: description
    attributes:
      label: Description du manque de détail
      description: Quels sont les aspects pas assez détaillés nuisant à la comprehension de la documentation
    validations:
      required: true
