name: 🚀 Modification de l'espace de travail
description: Changement de superviseur, modification des quotas de stockage ou diffusion, accès aux traitements...
labels: ["exploitation"]
projects: ["Geoplateforme/1"]
body:

  - type: input
    id: name
    attributes:
      label: Nom de l'espace de travail
      description: Nom de l'espace de travail (communauté ou entrepôt)
    validations:
      required: true

  - type: dropdown
    id: needs
    attributes:
      label: Besoins
      description: Quels sont les nouveaux besoins ?
      multiple: true
      options:
        - Changement de superviseur
        - Accès à de nouveaux traitements
        - Modification de quotas de stockage
        - Modification de quotas de diffusion
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description du nouveau besoin
      description: Quel est le nouvel utilisateur à mettre en superviseur, quels sont les nouveaux quotas à donner...
    validations:
      required: true
