name: 🆕 Demande d'un espace de travail
description: Demande de création d'un espace de travail
labels: ["exploitation"]
projects: ["Geoplateforme/1"]
body:

  - type: input
    id: name
    attributes:
      label: Nom de l'espace de travail
      description: Nom de l'espace de travail (peut contenir des accents)
    validations:
      required: true

  - type: input
    id: technical_name
    attributes:
      label: Nom technique de l'espace de travail
      description: Nom de l'espace de travail URL-compatible (pas d'accent, pas d'espaces, plutôt en minuscule). Ce nom sera utilisé dans des URL de diffusion. ⚠ Attention ⚠, il ne peut pas être changé.
    validations:
      required: true

  - type: dropdown
    id: data_needs
    attributes:
      label: Type de données 
      description: Quels sont types de données manipulées ?
      multiple: true
      options:
        - Raster
        - Vecteur
        - Archives
        - Index
    validations:
      required: true

  - type: description
    id: data_quotas
    attributes:
      label: Quotas nécessaires
      description: Taille totale au format fichier (par type de données)
    validations:
      required: true

  - type: dropdown
    id: broadcast_needs
    attributes:
      label: Type de diffusion 
      description: Quels sont types de diffusion envisagés ?
      multiple: true
      options:
        - WMS
        - WMTS / TMS
        - WFS
        - Téléchargement
        - Service de recherche
    validations:
      required: true

  - type: description
    id: broadcast_quotas
    attributes:
      label: Quotas nécessaires
      description: Nombre de couches finales (par type de diffusion)
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Informations complémentaires
      description: Expliquez vos cas d'usage concret
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        Nous vous contacterons par mail afin d'avoir votre identifiant utilisateur pour finaliser la demande
