name: 🆕 Ajout d'une nouvelle documentation
description: Demande d'ajout d'un nouveau cas d'usage dans la documentation
labels: ["enhancement","documentation"]
body:

  - type: markdown
    attributes:
      value: |
        Vous pouvez proposer la documentation pas à pas d'un nouveau cas d'usage via une pull request sur le dépôt de documentation

  - type: dropdown
    id: thematic
    attributes:
      label: Type de documentation
      description: Quel type de documentation faudrait-il ajouter ?
      options:
        - Tutoriel vecteur
        - Tutoriel raster
        - Tutoriel archive
        - Tutoriel Graphe navigable
        - Tutoriel Index de recherche
    validations:
      required: false

  - type: textarea
    id: description
    attributes:
      label: Description du cas d'usage
      description: Quel est l'objectif final du cas d'usage et quelles sont les étapes pour y arriver (livraison, traitement, publication, dépôt d'annexes...)
    validations:
      required: true
